# Generated by Django 5.1.6 on 2025-02-18 23:20

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Events',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('description', models.CharField(max_length=200)),
                ('day_created', models.DateTimeField(default=datetime.datetime(2025, 2, 18, 17, 20, 22, 789632))),
                ('day_of_event', models.DateTimeField()),
                ('spaces_available', models.IntegerField(default=0)),
                ('duration', models.DurationField()),
                ('image_link', models.CharField(max_length=200)),
                ('repetition', models.CharField(choices=[('D', 'Daily'), ('W', 'Weekly'), ('B', 'Biweekly'), ('M', 'Monthly')], max_length=100)),
                ('category', models.CharField(choices=[('Art', 'Art'), ('Community', 'Community'), ('Personal Growth', 'Personal Growth'), ('Wellness', 'Wellness'), ('Rooted for Teen Girls', 'Rooted for Teen Girls'), ('Service', 'Service'), ('Event/Workshop', 'Event/Workshop'), ('Trainings', 'Trainings')], max_length=100)),
            ],
        ),
    ]
