# Generated by Django 5.1.6 on 2025-02-19 03:37

import datetime
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_events_day_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='time_of_event',
            field=models.TimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='events',
            name='day_created',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 18, 21, 36, 11, 728253)),
        ),
        migrations.AlterField(
            model_name='events',
            name='day_of_event',
            field=models.DateField(default=datetime.date(2025, 2, 18)),
        ),
    ]
