# Generated by Django 5.1.6 on 2025-02-19 19:01

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_events_time_of_event_alter_events_day_created_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='events',
            name='instructor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='events',
            name='day_created',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 19, 13, 0, 42, 168414)),
        ),
        migrations.AlterField(
            model_name='events',
            name='day_of_event',
            field=models.DateField(default=datetime.date(2025, 2, 19)),
        ),
        migrations.CreateModel(
            name='Events_Scheduled',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.events')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
