# Generated by Django 5.1.6 on 2025-02-19 19:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_events_instructor_alter_events_day_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='day_created',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 19, 13, 3, 44, 535942)),
        ),
    ]
