# Generated by Django 5.1.6 on 2025-02-19 22:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_alter_events_day_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='day_created',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 19, 16, 23, 27, 217340)),
        ),
    ]
