# Generated by Django 5.1.6 on 2025-02-20 15:36

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_alter_events_day_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='day_created',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 20, 15, 36, 10, 205590, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='events',
            name='day_of_event',
            field=models.DateField(default=datetime.date(2025, 2, 20)),
        ),
    ]
