# Generated by Django 5.1.6 on 2025-02-20 15:37

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_alter_events_day_created_alter_events_day_of_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='day_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
