# Generated by Django 5.1.6 on 2025-02-20 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0011_alter_events_day_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='day_of_event',
            field=models.DateField(auto_now_add=True),
        ),
    ]
