# Generated by Django 5.1.6 on 2025-02-20 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_alter_events_day_of_event'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='day_of_event',
            field=models.DateField(),
        ),
    ]
