# Generated by Django 5.1.6 on 2025-03-06 03:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_alter_events_day_of_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='events',
            name='day_of_event',
        ),
        migrations.CreateModel(
            name='Event_Days',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_day', models.DateField()),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.events')),
            ],
        ),
    ]
