# Generated by Django 5.1.6 on 2025-03-06 03:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_remove_events_day_of_event_event_days'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Event_Days',
            new_name='Events_available',
        ),
    ]
