# Generated by Django 5.1.6 on 2025-03-07 01:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0015_rename_event_days_events_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events_scheduled',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.events_available'),
        ),
    ]
