# Generated by Django 5.1.6 on 2025-03-12 22:40

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_alter_events_scheduled_event'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events',
            old_name='day_created',
            new_name='date_created',
        ),
        migrations.RemoveField(
            model_name='events',
            name='repetition',
        ),
        migrations.AddField(
            model_name='events_scheduled',
            name='date_scheduled',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
