# Generated by Django 5.1.6 on 2025-03-13 02:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_rename_day_created_events_date_created_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events_scheduled',
            name='date_scheduled',
            field=models.DateField(auto_now_add=True),
        ),
    ]
