# Generated by Django 5.1.6 on 2025-03-13 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_alter_events_scheduled_date_scheduled'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='title',
            field=models.CharField(max_length=60, verbose_name='Event'),
        ),
    ]
