# Generated by Django 5.1.6 on 2025-03-16 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0019_alter_events_title'),
    ]

    operations = [
        migrations.RenameField(
            model_name='events_available',
            old_name='event_day',
            new_name='event_date',
        ),
    ]
