# Generated by Django 5.1.6 on 2025-04-02 07:57

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0022_alter_events_duration'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='duration',
            field=models.DurationField(choices=[(0.5, 0.5), (1, 1), (1.5, 1.5), (2, 2), (2.5, 2.5), (3, 3)], default=datetime.timedelta(seconds=3600)),
        ),
        migrations.AlterField(
            model_name='events',
            name='instructor',
            field=models.ForeignKey(default=1, limit_choices_to={'groups__name': 'teachers'}, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
