# Generated by Django 5.1.6 on 2025-04-02 08:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0023_alter_events_duration_alter_events_instructor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='events',
            name='duration',
            field=models.DurationField(choices=[(0.5, datetime.timedelta(seconds=1800)), (1, datetime.timedelta(seconds=3600)), (1.5, datetime.timedelta(seconds=5400)), (2, datetime.timedelta(seconds=7200)), (2.5, datetime.timedelta(seconds=9000)), (3, datetime.timedelta(seconds=10800))], default=datetime.timedelta(seconds=3600)),
        ),
    ]
